Name:           ros-kinetic-turtlebot3-automatic-parking-vision
Version:        1.0.0
Release:        0%{?dist}
Summary:        ROS turtlebot3_automatic_parking_vision package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://wiki.ros.org/turtlebot3_automatic_parking_vision
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-ar-track-alvar
Requires:       ros-kinetic-ar-track-alvar-msgs
Requires:       ros-kinetic-geometry-msgs
Requires:       ros-kinetic-joint-state-publisher
Requires:       ros-kinetic-nav-msgs
Requires:       ros-kinetic-robot-state-publisher
Requires:       ros-kinetic-rospy
Requires:       ros-kinetic-rviz
Requires:       ros-kinetic-sensor-msgs
Requires:       ros-kinetic-std-msgs
Requires:       ros-kinetic-turtlebot3-bringup
BuildRequires:  ros-kinetic-ar-track-alvar
BuildRequires:  ros-kinetic-ar-track-alvar-msgs
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-nav-msgs
BuildRequires:  ros-kinetic-rospy
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-std-msgs

%description
Package for TurtleBot3 automatic_parking which uses ar code. This example needs
a printed ar code and a TurtleBot3.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed May 30 2018 Pyo <pyo@robotis.com> - 1.0.0-0
- Autogenerated by Bloom

* Fri Apr 20 2018 Pyo <pyo@robotis.com> - 0.2.0-0
- Autogenerated by Bloom

